### ISSUE TITLE
Minor bug in decoding repeated bytes

### ISSUE THREAD

**Issue by THGSCST** [xnm3YQNfEx/GOCSaveEditor#4]
Hello! It seems that the decompressor is having an issue with decoding sequential repeated bytes.

Steps to Reproduce:
1. Open an decompressed savefile in a hexeditor
2. Go to the end of file.
3. See these two strings:
```
%s laughed at you bo�s.
I lost some h�ods.
```
The first strange byte is always 0xFE.

**Comment by xnm3YQNfEx** [comment]
So, that repeated byte issue, is actually present in the core game. I've done some RE analysis stepping through a debugger, and observed the same behavior with how the compressed data is loaded onto the heap:

Here's an example.
I started a new game, save that game, loaded the game. Didn't use my script at all.
I was using x32dbg with a breakpoint at 0x0042c9d2 (right where the game calls the function to decompress the save) Should have two structs on the stack, that use a vtable with offset 0x00781e18, which is some object for handling binary read/write.
Struct is 6 dword values with these offsets and uses:
0x00 vtable
0x04 ptr to base address of allocated memory
0x08 read cursor
0x0c allocated size
0x10 write cursor
0x14 ???, never seen it used, always just 0x00000000

After stepping over the function call, should have these on the stack side by side, one closer to the stack pointer (highlighted in green) is the output buffer for the decompressed data

![image](https://github.com/xnm3YQNfEx/GOCSaveEditor/assets/151261760/5ab91556-1181-4cf1-915f-ece89e9a2aa4)

The selected line in this case is the base address of the decompressed save data. going to that address + offset of ~0x18000 should get you close to where the street names were loaded

![image](https://github.com/xnm3YQNfEx/GOCSaveEditor/assets/151261760/406cc553-d0aa-44f8-899b-27a1c57eef6a)

We can see the same odd issue, specifically with words that have the same letter repeated, and the "following" character seems to change, as shown by Agness RD near the top having a 6 after the S, and Green St near the bottom having an } after the E

**Comment by xnm3YQNfEx** [comment]
Yup, it's a 'bug' in that the decompression isn't complete. It's using a combination of Huffman coding as well as RLE. Should have a fix in for this soon
